<a href="https://colab.research.google.com/github/graham-fletcher-athome/chs/blob/main/pgn_to_nn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install python-chess


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.5/156.5 kB 3.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for chess: filename=chess-1.11.1-py3-none-any.whl size=148499 sha256=bcf18590f61848e3e45bc7851049a6dfae2c3a069858903cd4c9ac04baf350ae
  Stored in directory: /root/.cache/pip/wheels/2e/2d/23/1bfc95db984ed3ecbf6764167dc7526d0ab521cf9a9852544e
Successfully built chess


In [2]:
# prompt: convert fen to nn inputs like lc0 does. Add input planes for castling rights to king and queen side. Dont add a plane for side to move, invert the board before calculating the planes if it is black to move. Include a plane for en passent. Use a plane size of 10x10 with the 8x8 board in the middle. Add an extra plane that defines the position of the board

import chess
import numpy as np

def fen_to_nn_input(fen):
    """Converts a FEN string to NN input like LC0 does.

    Args:
        fen: The FEN string to convert.

    Returns:
        A NumPy array representing the NN input.
    """

    board = chess.Board(fen)
    planes = np.zeros((18, 10, 10), dtype=np.float32)

    # Invert the board if it's black to move
    if board.turn == chess.BLACK:
        board = board.mirror()

    piece_map = {
        chess.PAWN: 0,
        chess.KNIGHT: 1,
        chess.BISHOP: 2,
        chess.ROOK: 3,
        chess.QUEEN: 4,
        chess.KING: 5,
    }

    for square in chess.SQUARES:
        piece = board.piece_at(square)
        if piece:
            color = int(piece.color)
            piece_type = piece_map[piece.piece_type]
            row, col = divmod(square, 8)
            planes[color * 6 + piece_type, row + 1, col + 1] = 1

    # Castling rights
    if board.has_kingside_castling_rights(chess.WHITE):
        planes[12, :, :] = 1
    if board.has_queenside_castling_rights(chess.WHITE):
        planes[13, :, :] = 1
    if board.has_kingside_castling_rights(chess.BLACK):
        planes[14, :, :] = 1
    if board.has_queenside_castling_rights(chess.BLACK):
        planes[15, :, :] = 1


    # En Passant
    if board.ep_square is not None:
        row, col = divmod(board.ep_square, 8)
        planes[16, row + 1, col + 1] = 1

    # Board Position Plane
    for row in range(8):
        for col in range(8):
          planes[17, row + 1, col + 1] = 1
    return planes

# Example usage
fen = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
nn_input = fen_to_nn_input(fen)
print(nn_input)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 1. 1. ... 1. 1. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 1. ... 1. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 1. 1. ... 1. 1. 0.]
  [0. 1. 1. ... 1. 1. 0.]
  ...
  [0. 1. 1. ... 1. 1. 0.]
  [0. 1. 1. ... 1. 1. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
